### PR TITLE
Added help tab

### PR DESCRIPTION
**Pull request by TopGun2001**
Added the help method to display all commands.
Also made some changes: displaying username after and greeting user after user keys in his/her name.

### CODE REVIEW

**Comment by TopGun2001** [comment]
I tried to add some UI after accepting user name but later commented them out, dk whats the problem

**Comment by TopGun2001** [comment]
I tried to fix the problem using hasNextLine() check but still doesn't work!

**Comment by jaredoong** [comment]
The main issue comes from `Ui.java`, where you have opened up another `Scanner` in the `printWelcomeMessage`. When the program exits the function, it causes the `Scanner` to be closed. Apparently in Java a closed standard stream cannot be reopened, at least from what I found [here](https://stackoverflow.com/questions/33555283/why-is-not-possible-to-reopen-a-closed-standard-stream).

One possible workaround would be to remove the portion on asking for the user name and just provide a generic welcome message for all users.

**Comment by TopGun2001** [comment]
I'm merging this pull request as every check is passed.

**Pull request merged**
